version: "3"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
    volumes:
      - mariadb_data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    volumes:
      - ./adminer.css:/var/www/html/adminer.css
    networks:
      - default
      - web
    environment:
      - ADMINER_DEFAULT_SERVER=mariadb

volumes:
  mariadb_data:
    external: true

networks:
  default:
    external:
      name: db

  web:
    external:
      name: web
